sudo: false
cache: bundler
language: ruby
rvm:
  - 2.2.2
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec thor spec
notifications:
  email:
    on_success: never
    on_failure: never
